### ISSUE TITLE
It that possible to publish a new version to crates.io?

### ISSUE THREAD

**Issue by zonyitoo** [huonw/simd#11]
It is still v0.0.3 on crates.io, do you consider to publish a new version?

Ref: https://github.com/zonyitoo/context-rs/issues/11

**Comment by dpc** [comment]
Pleeeeeeease? :D

**Comment by huonw** [comment]
I'm sorry, but there's some clean-up I want to do before publishing it. It looks like your needs can be covered by using `#[repr(simd)]` yourself directly:

``` rust
#[repr(simd)]
struct u32x4(u32, u32, u32, u32);
```

**Comment by zonyitoo** [comment]
That's ... Where is the definition of `#[repr(simd)]`? Is it recently added?

**Comment by zonyitoo** [comment]
I am going to close this and going to use feature `repr_simd`.
