### ISSUE TITLE
Project fails to compile on Rust 1.6 Nightly

### ISSUE THREAD

**Issue by liebharc** [huonw/simd#14]
Today the build of SIMD fails because of

```
/home/travis/.cargo/git/checkouts/simd-c969d6c7ccadf1f0/master/src/common.rs:12:5: 12:8 error: a module named `std` has already been imported in this module [E0252]

/home/travis/.cargo/git/checkouts/simd-c969d6c7ccadf1f0/master/src/common.rs:12 use std;
                                                                                    ^~~

/home/travis/.cargo/git/checkouts/simd-c969d6c7ccadf1f0/master/src/common.rs:12:5: 12:8 help: run `rustc --explain E0252` to see a detailed explanation

/home/travis/.cargo/git/checkouts/simd-c969d6c7ccadf1f0/master/src/common.rs:1:1: 1:14 note: previous import of `std` here

/home/travis/.cargo/git/checkouts/simd-c969d6c7ccadf1f0/master/src/common.rs:1 use super::*;
                                                                               ^~~~~~~~~~~~~

/home/travis/.cargo/git/checkouts/simd-c969d6c7ccadf1f0/master/src/sixty_four.rs:14:5: 14:8 error: a module named `std` has already been imported in this module [E0252]

/home/travis/.cargo/git/checkouts/simd-c969d6c7ccadf1f0/master/src/sixty_four.rs:14 use std;
                                                                                        ^~~

/home/travis/.cargo/git/checkouts/simd-c969d6c7ccadf1f0/master/src/sixty_four.rs:14:5: 14:8 help: run `rustc --explain E0252` to see a detailed explanation

/home/travis/.cargo/git/checkouts/simd-c969d6c7ccadf1f0/master/src/sixty_four.rs:2:1: 2:14 note: previous import of `std` here

/home/travis/.cargo/git/checkouts/simd-c969d6c7ccadf1f0/master/src/sixty_four.rs:2 use super::*;
                                                                                   ^~~~~~~~~~~~~
error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `simd`.
```

Rust version:

```
rustc 1.6.0-nightly (a9d15a6e9 2015-11-23)
```

Travis build log: https://travis-ci.org/liebharc/basic_dsp/builds/93077233

I'm aware that this crate is unstable and that this is more likely a regression/new feature in Rust itself. But since you seem to be working as part pf the Rust team right now I thought I still open this report to make you aware of this.

Oh and thanks for providing this crate, it's fun to play around with it.

**Comment by huonw** [comment]
Thanks for reporting this. I'm glad you're enjoying the crate.

**Comment by SimonSapin** [comment]
Out of curiosity: why did you have `use std;` there? And was there a breaking change in the language? (Since simd seemed to build with nightlies from not so long ago.)

**Comment by leeopop** [comment]
The compilation fails on rustc 1.6.0-nightly (aad4e5665 2015-12-05).
I think the 'use' rules are unstable now.
I suggest to have direct "uses" like use "std::ops::Shl", etc.

**Comment by huonw** [comment]
@SimonSapin because the `std` name wasn't/isn't in scope in submodules, probably. (And, yeah, 
non-`pub` `use`s were changed to act like non-`pub` items in glob imports.)

@leeopop I don't understand, #15 has been merged and so no longer has the `use std;` lines so you shouldn't be seeing any errors related to this anymore.

**Comment by liebharc** [comment]
This is a 2nd issue with 'use' which appeared in Rust Nightly after Simons change. So yes since I believe last Friday the build is failing again. I've send you a pull request (https://github.com/huonw/simd/pull/16) which should fix this - unless there was another Rust change meanwhile.

**Comment by leeopop** [comment]
#16 is just what I meant to.
Thanks for patching this.
