### ISSUE TITLE
Not compile.

### ISSUE THREAD

**Issue by quininer** [huonw/simd#30]
```
[I] ➜  simd git:(master) cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: Package `serde_codegen v0.8.1` does not have these features: `nightly`
```

[PR](https://github.com/huonw/simd/pull/8) may be able to solve the problem?

**Comment by liebharc** [comment]
This crate uses unstable Rust features and requires a [Rust nightly](https://doc.rust-lang.org/book/nightly-rust.html) version. So downloading and installing a Rust nightly version should resolve your error. Just keep in mind that Rust nightly and this lib is marked as `unstable` for a reason.
